apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: topic2
  namespace: confluent
spec:
  replicas: 4
  partitionCount: 6
  kafkaClusterRef:
    name: kafka
  configs:
    min.insync.replicas: "2"
    retention.ms: "86400000"